main: net.tfminecraft.tlibs.TLibs
api-version: '1.21.10'
name: TLibs
version: ${project.version}
author: Drefvelin
folia-supported: true

loadbefore: [RPCharacters]
softdepend: [MMOItems, MythicLib, ItemsAdder, MythicMobs, MMOCore, MCPets]

commands:
  tlibs:
    description: TLibs admin commands
    permission: tlibs.admin

permissions:
  tlibs.admin:
    default: op
